name: build-test-dist-test

on: [push]

jobs:
  main:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1

    - name: download colm 
      run: wget https://github.com/adrian-thurston/colm/tarball/master -O - | tar zxv

    - name: install colm
      run: COLM=`pwd`/inst/colm && cd adrian-thurston-colm-* && ./autogen.sh && ./configure --prefix=$COLM --disable-manual && make install

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: COLM=`pwd`/inst/colm && ./configure --with-colm=$COLM --disable-manual

    - name: make
      run: make

    - name: test
      run: cd test && ./runtests

    - name: make dist
      run: make dist

    - name: unpack
      run: mkdir unpack && tar -C unpack -zxvf colm-suite-*.tar.gz

    - name: configure the dist
      run: COLM=`pwd`/inst/colm && cd unpack/colm-suite-* && ./configure --with-colm=$COLM --disable-manual

    - name: make the dist
      run: cd unpack/colm-suite-* && make

    - name: test the dist
      run: cd unpack/colm-suite-*/test && ./runtests
