name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure --disable-manual

    - name: make
      run: make

    - name: test
      run: cd test && ./runtests

    - name: make dist
      run: make dist

    - name: unpack
      run: mkdir unpack && tar tar -C unpack -zxvf colm-suite-*.tar.gz

    - name: configure the dist
      run: cd unpack/colm-suite-* && ./configure --with-crack=/home/thurston/pkgs/crack --disable-manual --enable-debug

    - name: make the dist
      run: cd unpack/colm-suite-* && make

    - name: test the dist
      run: cd unpack/colm-suite-*/test && ./runtests
